### ISSUE TITLE
Supporting zero-decimal currencies?

### ISSUE THREAD

**Issue by aloukissas** [carlospalol/money#29]
Hi there! Was this a design choice not to support [zero-decimal currencies](https://stripe.com/docs/currencies#zero-decimal)? It would be a much welcome change. Happy to help!

**Comment by carlospalol** [comment]
Hi, there was no design choice to not support them... Tell me please a bit more about the issues you are finding with the current implementation. I imagine this is related to divisions?

**Comment by aloukissas** [comment]
Storing money values in ints (i.e. following the Stripe pattern) is our preferred method today. A good chunk of our backend is in Elixir and we're using a library with the same behavior there, too (https://github.com/elixirmoney/money). Yes, python's Decimal is great, but handling everything in zero-decimal currencies seems the safest (and most time-tested) way to go.

**Comment by agritheory** [comment]
> Storing money values in ints (i.e. following the Stripe pattern) is our preferred method today. A good chunk of our backend is in Elixir and we're using a library with the same behavior there, too (https://github.com/elixirmoney/money). Yes, python's Decimal is great, but handling everything in zero-decimal currencies seems the safest (and most time-tested) way to go.

I disagree, though it is a distinction between needing to store something precise and what should actually touch a general ledger, which I would argue should round-in, at least at a reporting level. 

Let's assume that you're an electronics manufacture and you want to be able to build a bill of materials with 67 resistors @ $0.002 each. Storing all of the digits in this case matters, otherwise will lead to a rounding error of $.004 per piece. It doesn't take long for that kind of thing to accumulate.

I also would not say that zero-currency is more time tested than a fractional representation of currencies, which has existed for thousands of years. There is no way for any currency representation that has limited precision to know if it is intrinsically "right", but making a decision about arbitrary currency precision at a library level will limit its usefulness. The next best place to do it is to enforce it at the currency-precision level (like pymoney), which is also sub-optimal, based on cases like the example I gave above, where arbitrary precision is an advantage.

QuickBooks (desktop), the most popular accounting software in America worth billions in sales each year stores USD with four decimals. That's arbitrary, and I'd argue incorrect.

I acknowledge that integer size matters, but to put it in accounting terms ends up being immaterial.

Sarcasm: This zero-currency phenomenon sounds like a convenience for Java developers.

**Comment by aloukissas** [comment]
I understand this point (the bill of materials), but how can you have a transaction with sub-cent value? In internal systems, like the example you give, it may make sense to have arbitrary precision. But in cases like payment systems (e.g. Stripe) it doesn't. Actually, Stripe (the leading payment processor on the internet) uses exactly this (all monetary values are integers).

**Comment by carlospalol** [comment]
I haven’t found any issue yet when using Money in ecommerce, but it has been always with 2 decimal currencies.

So far I am happy with Decimal as the amount type. I want to know if there is a concrete, real issue with this.

Please let me know what issues you had, or what exactly worries you.

**Comment by aloukissas** [comment]
It's fine - I did an internal implementation with integers, so it's compatible across all systems (and this is how we store monetary values in the database). It would have been great not to have to reimplement this, but it's nbd really.
